student/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from studentManagement.views import depart, user, pretty, admin, account, task, order, chart, upload

urlpatterns = [

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # path('admin/', admin.site.urls),
    # 部门管理
    path('depart/list', depart.depart_list),
    path('depart/add', depart.depart_add),
    path('depart/delete', depart.depart_delete),
    path('depart/<int:nid>/edit', depart.depart_edit),
    path('depart/multi', depart.depart_multi),

    # 用户管理
    path('user/list', user.user_list),
    path('user/add', user.user_add),
    path('user/model/form/add', user.user_model_form_add),
    path('user/<int:nid>/model/form/edit', user.user_model_form_edit),
    path('user/<int:nid>/delete', user.user_delete),

    # 靓号管理
    path('pretty/list', pretty.pretty_list),
    path('pretty/add', pretty.pretty_add),
    path('pretty/<int:nid>/edit', pretty.pretty_edit),

    # 管理员管理
    path('admin/list', admin.admin_list),
    path('admin/add', admin.admin_add),
    path('admin/<int:nid>/edit', admin.admin_edit),
    path('admin/<int:nid>/delete', admin.admin_delete),
    path('admin/<int:nid>/reset', admin.admin_reset),

    # 用户登录
    path('login', account.login),
    path('logout', account.logout),
    path('image/code', account.image_code),

    # 任务管理
    path('task/list', task.task_list),
    path('task/ajax', task.task_ajax),

    # 订单管理
    path('order/list', order.order_list),
    path('order/add', order.order_add),
    path('order/delete', order.order_delete),
    path('order/detail', order.order_detail),

    # 订单管理
    path('chart/list', chart.chart_list),
    path('chart/bar', chart.chart_bar),

    # 上传文件
    path('upload/list', upload.upload_list),
    path('upload/form', upload.upload_form),
]

studentManagement/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)

class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='标题', max_length=32)

    def __str__(self):
        return self.title

class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    create_time = models.DateTimeField(verbose_name='入职时间')

    # 增加约束
    # -to， 与哪张表关联
    # -to_field, 与表中的哪一列关联
    # depart在django添加进数据表中，将会变成 "depart_id"
    # 删除模式：1. 级联删除 (on_delete=models.CASCADE)
    #          - 如果关联的数据被删除，该数据也被删除
    #         2. 置空（null=True, blank=True, on_delete=models.SET_NULL)
    depart = models.ForeignKey(verbose_name='部门', to="Department", to_field='id', on_delete=models.CASCADE)

    # 在django中做约束
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)

class PrettyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="手机号", max_length=10)
    price = models.IntegerField(verbose_name="价格")

    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)

    status_choices = (
        (1, "已占用"),
        (2, "未使用"),
    )
    status = models. SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)

class Order(models.Model):
    """订单"""
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")

    status_choices = (
        (1, "待支付"),
        (2, "已支付"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE)


class Boss(models.Model):
    """老板"""
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    # 图片存储的是文件的路径
    img = models.CharField(verbose_name="头像", max_length=128)


    # 使用ModelForm储存文件
    # 本质上数据库也是CharField， 但可以自动保存数据
    # img = models.FileField(verbose_name="头像", max_length=128, upload_to='boss/' (上传的文件会存储到media目录的“/boss/”中)

studentManagement/views/account.py
from django.shortcuts import render
from django import forms
from studentManagement import models
from studentManagement.utils.bootstrap import BootStrapForm
from studentManagement.utils.encrypt import md5
from django.shortcuts import redirect, HttpResponse
from studentManagement.utils.checkCode import check_code


# Form 组件的写法
class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,  # 表示该项不能为空
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=True,  # 表示该项不能为空
    )
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput,
        required=True,
    )

    def clean_password(self):
        # 将密码的明文转变为密文
        pwd = self.cleaned_data.get('password')
        return md5(pwd)


# ModelForm 组件的写法
class LoginModelForm(forms.ModelForm):
    class Meta:
        models = models.Admin
        field = ['username', 'password']


def login(request):
    """登录"""

    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到的用户名和密码

        # 验证码的校验，校验完后同时删除掉验证码的数据，避免影响后面的用户名和密码的校验
        user_input_code = form.cleaned_data.pop('code')
        exact_image_code = request.session.get('image_code', "")  # 不存在的话（超时被删除），返回空字符串
        if exact_image_code == "":
            form.add_error("code", "验证码超时")
            return render(request, 'login.html', {'form': form})
        if exact_image_code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {'form': form})

        # 数据库校验用户名和密码是否正确，获取用户对象 或者 None
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()  # 将数据文件（格式为字典）作为语句查询数据库

        # 如果用户名或者密码错误
        if not admin_object:
            form.add_error("password", "用户名或密码错误")  # 主动添加错误信息在password栏显示错误信息
            return render(request, 'login.html', {'form': form})

        # 如果用户名和密码正确
        # 网站需要生成一个随机字符串； 并将‘info'信息写到用户浏览器的cookie中； 再写入到session中；
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username}
        # session设置为7天有效期
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect("/admin/list")

    return render(request, 'login.html', {'form': form})


def logout(request):
    """注销"""

    request.session.clear()

    return redirect('/login')


from io import BytesIO


def image_code(request):
    """生成图片验证码"""

    # 调用utils的checkCode函数，生成图片
    img, code_str = check_code()

    # 写入到用户的session中（以便后续获取验证码再进行校验）
    request.session['image_code'] = code_str
    # 给session设置60s超时
    request.session.set_expiry(60)

    # 将图片保存在stream中
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

studentManagement/views/admin.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.core.exceptions import ValidationError
from studentManagement.utils.encrypt import md5

from studentManagement import models
from studentManagement.utils.pagination import Pagination


def admin_list(request):
    """管理员列表"""

    #检查用户是否已经登录，如果已登录，继续走下去，未登录，跳转为登录页面。
    #用户发来请求，获取cookie随机字符串，拿着随机字符串到session中查找
    # info = request.session.get("info")
    # if not info:
    #     return redirect('/login')

    queryset = models.Admin.objects.all()
    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,
        "page_string": page_object.html(),
    }

    return render(request, 'admin_list.html', context)


from django import forms
from studentManagement.utils.bootstrap import BootStrapModelForm


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput
    )

    class Meta:
        model = models.Admin
        fields = ["username", "password", "confirm_password"]
        widgets = {
            "password": forms.PasswordInput
        }

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)

    def clean_confirm_password(self):
        # 针对“确认密码”的钩子函数

        # 首先获得“密码”和“确认密码”的数据
        pwd = self.cleaned_data.get("password")
        confirm_pwd = md5(self.cleaned_data.get("confirm_password"))

        if confirm_pwd != pwd:  # 两个数据不一致，抛出错误（记得导入ValidationError）
            raise ValidationError("密码不一致，请重新输入")

        # 此时记得把原来的值return回去
        return confirm_pwd


def admin_add(request):
    """添加管理员"""
    title = "新建管理员"

    if request.method == 'GET':
        form = AdminModelForm()
        context = {
            "title": title,
            "form": form
        }
        return render(request, 'admin_add.html', context)

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list')

    return render(request, 'admin_add.html', {'form': form, 'title': title})


class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']


def admin_edit(request, nid):
    """编辑管理员"""
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect('/admin/list')

    title = "编辑管理员"

    if request.method == 'GET':
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'admin_edit.html', {'form': form, 'title': title})

    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list')

    return render(request, 'admin_edit.html', {'form': form, 'title': title})


def admin_delete(request, nid):
    """删除管理员"""
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list')


class AdminResetModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput
    )

    class Meta:
        model = models.Admin
        fields = ["password", "confirm_password"]
        widgets = {
            "password": forms.PasswordInput
        }

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)

    def clean_confirm_password(self):
        # 针对“确认密码”的钩子函数

        # 首先获得“密码”和“确认密码”的数据
        pwd = self.cleaned_data.get("password")
        confirm_pwd = md5(self.cleaned_data.get("confirm_password"))

        if confirm_pwd != pwd:  # 两个数据不一致，抛出错误（记得导入ValidationError）
            raise ValidationError("密码不一致，请重新输入")

        # 此时记得把原来的值return回去
        return confirm_pwd


def admin_reset(request, nid):
    """重置密码"""
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect('/admin/list')

    title = "重置密码 - {}".format(row_object.username)

    if request.method == 'GET':
        form = AdminResetModelForm(instance=row_object)
        return render(request, 'admin_edit.html', {'form': form, 'title': title})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list')

    return render(request, 'admin_edit.html', {'form': form, 'title': title})

studentManagement/views/chart.py
from django.shortcuts import render
from django.http import JsonResponse


def chart_list(request):
    """数据统计页面"""
    return render(request, "chart_list.html")


def chart_bar(request):
    """构造一个柱状图数据"""
    legend = ['销量']
    xAxis = ['衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子']
    data_list = [
        {
            "name": '销量',
            "type": 'bar',
            "data": [5, 20, 36, 10, 10, 20],
        },
    ]

    result = {
        "status": True,
        "data": {
            'legend': legend,
            "xAxis": xAxis,
            "data_list": data_list,
        }
    }

    return JsonResponse(result)

studentManagement/views/depart.py
from django.shortcuts import render, redirect, HttpResponse
from studentManagement import models
from studentManagement.utils.pagination import Pagination

def depart_list(request):
    """部门列表"""

    # 去数据库中获取所有的部门列表
    queryset = models.Department.objects.all()

    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,
        "page_string": page_object.html(),
    }

    return render(request, 'depart_list.html', context)

def depart_add(request):
    """添加部门"""
    if request.method == 'GET':
        return render(request, 'depart_add.html')

    # 获取用户POST过来的数据
    title = request.POST.get("title")

    # 保存到数据库
    models.Department.objects.create(title=title)

    # 重定向回部门列表
    return redirect("/depart/list")

def depart_delete(request):
    """删除部门"""
    # 获取id
    nid = request.GET.get("nid")

    # 删除
    models.Department.objects.filter(id=nid).delete()

    # 重定向回部门列表
    return redirect("/depart/list")

def depart_edit(request, nid):
    """修改部门"""

    # 根据nid，获取数据
    depart_name = models.Department.objects.filter(id=nid).first().title

    if request.method == "GET":
        return render(request, 'depart_edit.html', {'depart_name': depart_name})

    if request.method == "POST":
        # 获取新的部门名称
        new_title = request.POST.get("title")

        # 数据库更新
        models.Department.objects.filter(id=nid).update(title=new_title)

    # 重定向回部门列表
    return redirect("/depart/list")

def depart_multi(request):
    """批量上传（execl文件）"""
    from openpyxl import load_workbook

    # 1. 获取用户上传的文件对象
    file_object = request.FILES.get("exc")

    # 2. 对象传递给openpyxl，打开excel并读取内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]  #第0列的数据

    # 3. 循环获取每一段的数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value
        exists = models.Department.objects.filter(title=text).exists()
        if not exists:
            models.Department.objects.create(title=text)

    return redirect("/depart/list")

studentManagement/views/order.py
import json
import random
from datetime import datetime
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from studentManagement.utils.bootstrap import BootStrapModelForm
from studentManagement import models
from studentManagement.utils.pagination import Pagination


class OrderModelForm(BootStrapModelForm):
    class Meta:
        model = models.Order
        # 该语句会将Order的全部属性生成为表
        # fields = "__all__"

        # oid（订单号）不需要生成为表
        exclude = ["oid", "admin"]


def order_list(request):
    """订单列表"""

    queryset = models.Order.objects.all().order_by('-id')
    page_object = Pagination(request, queryset)
    form = OrderModelForm()

    context = {
        'form': form,
        'queryset': page_object.page_queryset,
        "page_string": page_object.html(),
    }

    return render(request, "order_list.html", context)


@csrf_exempt
def order_add(request):
    """新建订单（Ajax请求）"""
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        # 系统自动填写oid数据
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))

        # 获取管理员数据
        form.instance.admin_id = request.session["info"]["id"]

        form.save()
        return JsonResponse({"status": True})

    return JsonResponse({"status": False, 'error': form.errors})


def order_delete(request):
    """删除订单"""
    uid = request.GET.get('uid')
    print(uid)
    models.Order.objects.filter(id=uid).delete()
    return JsonResponse({"status": True})


def order_detail(request):
    """根据ID获取订单数据"""
    uid = request.GET.get("uid")
    row_dict = models.Order.objects.filter(id=uid).values("title", "price", "status").first()
    if not row_dict:
        return JsonResponse({"status": False, 'error': "数据不存在。"})

    result = {
        "status": True,
        "data": row_dict,
    }

    return JsonResponse({"status": True, "data": result})

studentManagement/views/task.py
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt

def task_list(request):
    """任务列表"""
    return render(request, "task_list.html")

@csrf_exempt
def task_ajax(request):
    print(request.POST)

    return HttpResponse("成功了")

studentManagement/templates/admin_reset.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}

                    {% for item in form %}
                    <div class="form-group">
                        <label>{{ item.label }}</label>
                        {{ item }}
                        <span style="red">{{ item.errors.0 }}</span>
                    </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

studentManagement/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }




    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <lable>密码</lable>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code" style="width: 125px;">
                </div>
            </div>
        </div>

        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>
</body>
</html>

studentManagement/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div>
        <input type="button" value="新建订单" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    </div>
    <div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            订单列表
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>订单号</th>
                <th>名称</th>
                <th>价格</th>
                <th>状态</th>
                <th>管理员</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
            <tr>
                <th>{{ obj.id }}</th>
                <td>{{ obj.oid }}</td>
                <td>{{ obj.title }}</td>
                <td>{{ obj.price }}</td>
                <td>{{ obj.get_status_display }}</td>
                <td>{{ obj.admin.username }}</td>
                <th>
                    <input id="{{ obj.id }}" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">
                    <input id="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete" type="button" value="删除">
                </th>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<nav aria-label="Page navigation">
    <ul class="pagination">
        {{page_string}}
    </ul>
</nav>
</div>

<!-- 新建、编辑订单（对话框） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">New Order</h4>
            </div>
            <div class="modal-body">
                <form id="formAdd">
                    <div class="clearfix">
                        {% for field in form %}
                        <div class="col-xs-6">
                            <div class="form-group" style="">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg" style=""></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="btnSave" type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 删除订单（对话框） -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <h4>是否确定删除!</h4>
            <p style="margin: 10px 0;">删除后，所有关联的相关数据会被删除</p>
            <p style="text-align: right;">
                <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
            </p>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
        var DELETE_ID;

        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {

                // 清空对话框中的数据
                $("#formAdd")[0].reset();

                // 重新设置对话框的标题
                $("#myModalLabel").text("New Order");

                // 清楚错误信息
                $(".error-msg").empty();

                // 向后台发送请求
                $.ajax({
                    url: "/order/add",
                    type: "post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if(res.status){
                            alert("创建成功");

                            // 清空表单
                            $("#formAdd")[0].reset();

                            // 关闭弹窗
                            $("#myModal").modal('hide');

                            //刷新页面
                            location.reload();
                        } else {
                            // 把错误信息显示在对话框中，
                            $.each(res.error, function (name, errorList) {
                                $("#id_"+name).next().text(errorList[0]);
                            })

                        }
                    }
                })
            });
        }

        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function () {

                // 显示删除对话框
                $("#deleteModal").modal('show');

                // 获取当前行的id并复制给全局变量
                DELETE_ID = $(this).attr("id");

            });
        }

        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                //点击确认删除按钮，将全局变量中设置要删除的ID发送到后台
                $.ajax({
                    url: "/order/delete",
                    type: "GET",
                    data: {
                        uid: DELETE_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if(res.status){
                            alert("删除成功");

                            //隐藏删除框
                            $("#deleteModal").modal('hide');

                            //要删除的id清空
                            DELETE_ID = 0;

                            //页面刷新
                            location.reload();

                        }else{
                            //删除失败
                            alert(res.error);
                        }
                    }
                })
            })
        }

        function bindBtnEditEvent() {
            $(".btn-edit").click(function () {

                var id = $(this).attr("id");

                // 发送Ajax去后端获取当前行的相关数据
                $.ajax({
                    url: "/order/detail",
                    type: "get",
                    data: {
                        uid: id
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status){

                            // 修改对话框的标题
                            $("#myModalLabel").text("Edit Order");

                            // 将数据默认复制到对话框的标签中
                            $.each(res.data.data, function (name, value) {
                                $("#id_" + name).val(value);
                            })

                            // 点击编辑，显示对话框
                            $('#myModal').modal('show');


                        }else{
                            alert(res.error);
                        }
                    }
                })
            });
        }






</script>
{% endblock %}

studentManagement/templates/upload_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="username">
        <input type="file" name="avatar">
        <input type="submit" value="提交">
    </form>
</div>

{% endblock %}

studentManagement/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div style="margin-bottom: 10px">
        <a class="btn btn-success" href="/user/add">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            新建用户
        </a>
        <a class="btn btn-success" href="/user/model/form/add">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            新建用户（Model Foam）
        </a>
    </div>
    <div class="bs-example" data-example-id="panel-without-body-with-table">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.account }}</td>
                        <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <th>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/model/form/edit">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete">删除</a>
                        </th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        <nav aria-label="Page navigation">
        <ul class="pagination">
            {{page_string}}
        </ul>
    </nav>
</div>
{% endblock %}